events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # SSL configuration
    ssl_certificate /etc/nginx/certs/server-cert.pem;
    ssl_certificate_key /etc/nginx/certs/server-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Forwarding headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;

    # Upstream for GoSignals1 cluster
    upstream gosignals1_cluster {
        server goSignals1:8888;
        server goSignals1b:8888;
    }

    # GoSignals Port 8888
    server {
        listen 8888 ssl;
        server_name gosignals1;

        location / {
            proxy_pass https://gosignals1_cluster;
            proxy_ssl_verify off;
        }
    }

    server {
        listen 8888 ssl;
        server_name gosignals2;

        location / {
            proxy_pass https://goSignals2:8889;
            proxy_ssl_verify off;
        }
    }

    server {
        listen 8888 ssl;
        server_name gossfserver;

        location / {
            proxy_pass https://goSsfServer:8890;
            proxy_ssl_verify off;
        }
    }

    # SCIM Cluster Port 9000
    server {
        listen 9000 ssl;
        server_name scim_cluster1;

        location / {
            proxy_pass http://scim_cluster1:8080;
        }
    }

    server {
        listen 9000 ssl;
        server_name scim_cluster2;

        location / {
            proxy_pass http://scim_cluster2:8080;
        }
    }

    # Keycloak Port 9080
    server {
        listen 9080 ssl;
        server_name keycloak;

        location / {
            proxy_pass https://keycloak:9080;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_ssl_verify off;
        }
    }
}
