package memory_provider

import (
	"context"
	"testing"

	"github.com/i2-open/i2goSignals/internal/authUtil"
	"github.com/i2-open/i2goSignals/pkg/goSet"
	"github.com/i2-open/i2goSignals/pkg/ssfModels"
)

// createStreamHelper invokes StreamService.CreateStream with a synthesized
// AuthContext-bearing context. Used by the provider DAO tests to keep the
// arrange step terse.
func createStreamHelper(p *MemoryProvider, cfg model.StreamConfiguration, projectId string) (model.StreamConfiguration, error) {
	authCtx := authUtil.ConvertProject(projectId)
	ctx := context.WithValue(context.Background(), authUtil.AuthContextKey, authCtx)
	return p.streamService.CreateStream(ctx, cfg, authCtx.ProjectId, nil)
}

func TestMemoryProviderDAOOpen(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv(CEnvMemDir, tmpDir)

	provider, err := Open("memorydb:", "test_db_v2")
	if err != nil {
		t.Fatalf("Failed to open memory provider V2: %v", err)
	}
	defer func(provider *MemoryProvider) {
		_ = provider.Close()
	}(provider)

	if provider.Name() != "test_db_v2" {
		t.Errorf("Expected database name test_db_v2, got %s", provider.Name())
	}

	err = provider.Check()
	if err != nil {
		t.Errorf("Check() failed: %v", err)
	}
}

func TestMemoryProviderDAOStreamOperations(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv(CEnvMemDir, tmpDir)

	provider, err := Open("memorydb:", "test_db_v2_stream")
	if err != nil {
		t.Fatalf("Failed to open memory provider V2: %v", err)
	}
	defer func(provider *MemoryProvider) {
		_ = provider.Close()
	}(provider)

	// Create a stream
	streamConfig := model.StreamConfiguration{
		EventsRequested: []string{"*"},
		Delivery: &model.OneOfStreamConfigurationDelivery{
			PollTransmitMethod: &model.PollTransmitMethod{
				Method: model.DeliveryPoll,
			},
		},
	}

	createdStream, err := createStreamHelper(provider, streamConfig, "test_project")
	if err != nil {
		t.Fatalf("Failed to create stream: %v", err)
	}

	if createdStream.Id == "" {
		t.Error("Created stream should have an ID")
	}

	// Get the stream
	retrievedStream, err := provider.GetStreamService().GetStream(context.Background(), createdStream.Id)
	if err != nil {
		t.Fatalf("Failed to get stream: %v", err)
	}

	if retrievedStream.Id != createdStream.Id {
		t.Errorf("Expected stream ID %s, got %s", createdStream.Id, retrievedStream.Id)
	}

	// List streams
	streams := provider.GetStreamService().ListStreams(context.Background())
	if len(streams) != 1 {
		t.Errorf("Expected 1 stream, got %d", len(streams))
	}

	// Delete stream
	err = provider.GetStreamService().DeleteStream(context.Background(), createdStream.Id)
	if err != nil {
		t.Fatalf("Failed to delete stream: %v", err)
	}

	// Verify deletion
	streams = provider.GetStreamService().ListStreams(context.Background())
	if len(streams) != 0 {
		t.Errorf("Expected 0 streams after deletion, got %d", len(streams))
	}
}

func TestMemoryProviderDAOEventOperations(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv(CEnvMemDir, tmpDir)

	provider, err := Open("memorydb:", "test_db_v2_events")
	if err != nil {
		t.Fatalf("Failed to open memory provider V2: %v", err)
	}
	defer func(provider *MemoryProvider) {
		_ = provider.Close()
	}(provider)

	// Create an event using CreateSet
	event := goSet.CreateSet(nil, "test-issuer", []string{"test-audience"})
	event.Events = map[string]interface{}{"test": "event"}
	testJti := event.ID // Store the JTI generated by CreateSet

	eventRecord, err := provider.GetEventService().AddEvent(context.Background(), &event, "stream-1", `{"jti":"`+testJti+`"}`)
	if err != nil || eventRecord == nil {
		t.Fatal("Failed to add event")
	}

	// Retrieve the event
	retrievedEvent := provider.GetEventService().GetEvent(context.Background(), testJti)
	if retrievedEvent == nil {
		t.Fatal("Failed to retrieve event")
	}

	if retrievedEvent.ID != testJti {
		t.Errorf("Expected event ID %s, got %s", testJti, retrievedEvent.ID)
	}
}

func TestMemoryProviderDAOKeyOperations(t *testing.T) {
	tmpDir := t.TempDir()
	t.Setenv(CEnvMemDir, tmpDir)

	provider, err := Open("memorydb:", "test_db_v2_keys")
	if err != nil {
		t.Fatalf("Failed to open memory provider V2: %v", err)
	}
	defer func(provider *MemoryProvider) {
		_ = provider.Close()
	}(provider)

	// Create a key pair
	privateKey, err := provider.GetKeyService().CreateKeyPair(context.Background(), "test-issuer", "sig", "test-project")
	if err != nil || privateKey == nil {
		t.Fatal("Failed to create issuer key pair")
	}

	// Get the private key
	retrievedKey, err := provider.GetKeyService().GetPrivateKey(context.Background(), "test-issuer")
	if err != nil {
		t.Fatalf("Failed to get issuer private key: %v", err)
	}

	if retrievedKey == nil {
		t.Fatal("Retrieved key is nil")
	}

	// Get public JWKS
	jwks := provider.GetKeyService().GetPublicJWKS(context.Background(), "test-issuer")
	if jwks == nil {
		t.Fatal("Failed to get public transmitter JWKS")
	}

	// Delete key by name
	err = provider.GetKeyService().DeleteKeysByName(context.Background(), "test-issuer")
	if err != nil {
		t.Fatalf("Failed to delete key: %v", err)
	}

	// Verify deletion
	_, err = provider.GetKeyService().GetPrivateKey(context.Background(), "test-issuer")
	if err == nil {
		t.Error("Expected error when getting deleted key, got nil")
	}
}
