/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// [Spec](https://openid.net/specs/openid-sse-framework-1_0.html#rfc.section.3.4.1)  The \"JWT ID\" Subject Identifier Format specifies a JSON Web Token (JWT) identifier, defined in [RFC7519](https://datatracker.ietf.org/doc/html/rfc7519).
type JwtId struct {
	Format string `json:"format"`
	// The \"iss\" (issuer) claim of the JWT being identified, defined in [RFC7519](https://datatracker.ietf.org/doc/html/rfc7519)
	Iss string `json:"iss"`
	// The \"jti\" (JWT token ID) claim of the JWT being identified, defined in [RFC7519](https://datatracker.ietf.org/doc/html/rfc7519)
	Jti string `json:"jti"`
}
