/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type PushDeliveryMethod struct {
	Method string `json:"method"`
	// The URL where events are pushed through HTTP POST. This is set by the Receiver.
	EndpointUrl string `json:"endpoint_url"`
	// The HTTP Authorization header that the Transmitter MUST set with each event delivery, if the configuration is present. The value is optional and it is set by the Receiver.
	AuthorizationHeader string `json:"authorization_header,omitempty"`
}
