/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type StreamStatus struct {
	// REQUIRED. The status of the stream. Values can be one of:  enabled:   The Transmitter MUST transmit events over the stream,   according to the stream’s configured delivery method.  paused:   The Transmitter MUST NOT transmit events over the stream.   The transmitter will hold any events it would have transmitted while paused,   and SHOULD transmit them when the stream’s status becomes enabled.   If a Transmitter holds successive events that affect the same Subject Principal,   then the Transmitter MUST make sure that those events are transmitted in   the order of time that they were generated OR the Transmitter MUST send   only the last events that do not require the previous events affecting   the same Subject Principal to be processed by the Receiver,   because the previous events are either cancelled by the later events or   the previous events are outdated.  disabled:   The Transmitter MUST NOT transmit events over the stream,   and will not hold any events for later transmission.
	Status string `json:"status"`
	// OPTIONAL. The Subject to which the status applies.
	Subject *AllOfStreamStatusSubject `json:"subject,omitempty"`
}
