package mongo

import (
	"go.mongodb.org/mongo-driver/v2/bson"
)

// legacySubjectDoc returns the Go-shaped subject subdocument that the pre-#259
// default struct codec wrote: the wire `format`, plus embedded identifier
// variants under their Go field names, with the empty values the old encoder
// always emitted. At most one variant carries data.
//
// This is a hand-transcribed fixture, deliberately NOT generated by the code
// under test — its whole job is to represent what is already on disk. The
// legacy sniff keys off the presence of these Go names rather than their
// number, so listing the variants the assertions actually read is enough.
//
// Shared by the three suites that need a pre-fix row (events, persisted
// routing, subject filters). They previously transcribed it separately and had
// already drifted apart on how many variants they listed.
func legacySubjectDoc(format, emailValue, opaqueValue string) bson.D {
	return bson.D{
		{Key: "format", Value: format},
		{Key: "usernameidentifier", Value: bson.D{{Key: "username", Value: ""}}},
		{Key: "emailidentifier", Value: bson.D{{Key: "email", Value: emailValue}}},
		{Key: "opaqueidentifier", Value: bson.D{{Key: "id", Value: opaqueValue}}},
		{Key: "complexidentifier", Value: bson.D{{Key: "user", Value: nil}}},
	}
}
