/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	ssef "i2goSignals/goSSEF/server"
	"log"
	"net/http"
)

func main() {
	log.Printf("i2signals SSEF Server starting")

	router := ssef.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
