/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	"encoding/json"
	"errors"
	"strings"
)

type OneOfStreamConfigurationDelivery struct {
	*PushTransmitMethod
	*PushReceiveMethod
	*PollTransmitMethod
	*PollReceiveMethod
	// SstpTransmitMarker and SstpReceiveMarker are marker-only variants for the
	// two directions of an SSTP pair. They carry the method URN and nothing
	// else; pair-scoped connectivity lives in StreamStateRecord.SstpMethod so
	// the SSF wire shape never leaks the per-pair bearer/endpoint. (ADR 0018)
	*SstpTransmitMarker
	*SstpReceiveMarker
}

func (d *OneOfStreamConfigurationDelivery) MarshalJSON() ([]byte, error) {
	// Required because json.Marshal doesn't seem to handle two optional structures.
	if d.PushTransmitMethod != nil {
		return json.Marshal(d.PushTransmitMethod)
	}
	if d.PollTransmitMethod != nil {
		return json.Marshal(d.PollTransmitMethod)
	}
	if d.PollReceiveMethod != nil {
		return json.Marshal(d.PollReceiveMethod)
	}
	if d.PushReceiveMethod != nil {
		return json.Marshal(d.PushReceiveMethod)
	}
	if d.SstpTransmitMarker != nil {
		return json.Marshal(d.SstpTransmitMarker)
	}
	if d.SstpReceiveMarker != nil {
		return json.Marshal(d.SstpReceiveMarker)
	}
	return []byte("{}"), nil
}

func (d *OneOfStreamConfigurationDelivery) DeepCopy() *OneOfStreamConfigurationDelivery {
	if d == nil {
		return nil
	}
	res := &OneOfStreamConfigurationDelivery{}
	if d.PushTransmitMethod != nil {
		copyMethod := *d.PushTransmitMethod
		res.PushTransmitMethod = &copyMethod
	}
	if d.PushReceiveMethod != nil {
		copyMethod := *d.PushReceiveMethod
		res.PushReceiveMethod = &copyMethod
	}
	if d.PollTransmitMethod != nil {
		copyMethod := *d.PollTransmitMethod
		res.PollTransmitMethod = &copyMethod
	}
	if d.PollReceiveMethod != nil {
		copyMethod := *d.PollReceiveMethod
		res.PollReceiveMethod = &copyMethod
	}
	if d.SstpTransmitMarker != nil {
		copyMethod := *d.SstpTransmitMarker
		res.SstpTransmitMarker = &copyMethod
	}
	if d.SstpReceiveMarker != nil {
		copyMethod := *d.SstpReceiveMarker
		res.SstpReceiveMarker = &copyMethod
	}
	return res
}

// GetMethod returns the delivery method for the stream configuration. Returns one of DeliveryPush, DeliveryPoll, ReceivePush, ReceivePoll.
func (d *OneOfStreamConfigurationDelivery) GetMethod() string {
	if d == nil {
		return "DEFAULT"
	}
	if d.PushTransmitMethod != nil {
		return DeliveryPush
	}

	if d.PushReceiveMethod != nil {
		return ReceivePush
	}

	if d.PollTransmitMethod != nil {
		return DeliveryPoll
	}

	if d.PollReceiveMethod != nil {
		return ReceivePoll
	}

	if d.SstpReceiveMarker != nil {
		return ReceiveSstp
	}

	if d.SstpTransmitMarker != nil {
		return DeliverySstp
	}
	return "DEFAULT"
}

func (d *OneOfStreamConfigurationDelivery) GetEndpointUrl() string {
	if d == nil {
		return ""
	}
	switch d.GetMethod() {
	case DeliveryPush:
		if d.PushTransmitMethod != nil {
			return d.PushTransmitMethod.EndpointUrl
		}
	case DeliveryPoll:
		if d.PollTransmitMethod != nil {
			return d.PollTransmitMethod.EndpointUrl
		}
	case ReceivePush:
		if d.PushReceiveMethod != nil {
			return d.PushReceiveMethod.EndpointUrl
		}
	case ReceivePoll:
		if d.PollReceiveMethod != nil {
			return d.PollReceiveMethod.EndpointUrl
		}
	}
	return "" // won't happen unless a new method defined
}

func (d *OneOfStreamConfigurationDelivery) GetAuthorizationHeader() string {
	if d == nil {
		return ""
	}
	switch d.GetMethod() {
	case DeliveryPush:
		if d.PushTransmitMethod != nil {
			return d.PushTransmitMethod.AuthorizationHeader
		}
	case DeliveryPoll:
		if d.PollTransmitMethod != nil {
			return d.PollTransmitMethod.AuthorizationHeader
		}
	case ReceivePush:
		if d.PushReceiveMethod != nil {
			return d.PushReceiveMethod.AuthorizationHeader
		}
	case ReceivePoll:
		if d.PollReceiveMethod != nil {
			return d.PollReceiveMethod.AuthorizationHeader
		}
	}
	return "" // won't happen unless a new method defined
}

func (d *OneOfStreamConfigurationDelivery) GetAuthorizationType() string {
	if d.GetAuthorizationHeader() != "" {
		return AuthModeToken
	}
	return AuthModeClient
}

func (d *OneOfStreamConfigurationDelivery) UnmarshalJSON(data []byte) error {
	dataString := string(data)
	if dataString == "null" || dataString == `""` {
		d.PollTransmitMethod = nil
		d.PushTransmitMethod = nil
		d.PollReceiveMethod = nil
		d.PushReceiveMethod = nil
		d.SstpTransmitMarker = nil
		d.SstpReceiveMarker = nil
		return nil
	}

	lowString := strings.ToLower(dataString)
	// SSTP markers are matched before the RFC8935/8936 URNs. ReceiveSstp is a
	// superstring of DeliverySstp, so the receive check must come first.
	if strings.Contains(lowString, DeliverySstp) {
		if strings.Contains(lowString, ReceiveSstp) {
			var marker SstpReceiveMarker
			if err := json.Unmarshal(data, &marker); err != nil {
				return err
			}
			d.SstpReceiveMarker = &marker
			return nil
		}
		var marker SstpTransmitMarker
		if err := json.Unmarshal(data, &marker); err != nil {
			return err
		}
		d.SstpTransmitMarker = &marker
		return nil
	}
	if strings.Contains(lowString, DeliveryPoll) {
		if strings.Contains(lowString, ReceivePoll) {
			var poll PollReceiveMethod
			err := json.Unmarshal(data, &poll)
			if err != nil {
				return err
			}
			d.PollReceiveMethod = &poll
			return nil
		}
		var poll PollTransmitMethod
		err := json.Unmarshal(data, &poll)
		if err != nil {
			return err
		}
		d.PollTransmitMethod = &poll
		return nil

	}
	if strings.Contains(lowString, DeliveryPush) {
		if strings.Contains(lowString, ReceivePush) {
			var push PushReceiveMethod
			err := json.Unmarshal(data, &push)
			if err != nil {
				return err
			}
			d.PushReceiveMethod = &push
			return nil
		}
		var push PushTransmitMethod
		err := json.Unmarshal(data, &push)
		if err != nil {
			return err
		}
		d.PushTransmitMethod = &push
		return nil

	}

	return errors.New("Unknown Stream delivery_method value.")
}
