/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// [Spec](https://datatracker.ietf.org/doc/html/draft-ietf-secevent-subject-identifiers#section-3.2.5)  The Issuer and Subject Identifier Format identifies a subject using a pair of \"iss\" and \"sub\" members, analagous to how subjects are identified using the \"iss\" and \"sub\" claims in OpenID Connect [OpenID.Core](http://openid.net/specs/openid-connect-core-1_0.html) ID Tokens. These members MUST follow the formats of the \"iss\" member and \"sub\" member defined by [RFC7519](https://datatracker.ietf.org/doc/html/rfc7519), respectively. Both the \"iss\" member and the \"sub\" member are REQUIRED and MUST NOT be null or empty.  The Issuer and Subject Identifier Format is identified by the name \"iss_sub\".
type IssSub struct {
	Format string `json:"format"`

	Iss string `json:"iss"`

	Sub string `json:"sub"`
}
