/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// [Spec](https://datatracker.ietf.org/doc/html/draft-ietf-secevent-subject-identifiers#section-3.2.3)  The Decentralized Identifier Format identifies a subject using a Decentralized Identifier (DID) URL as defined in [DID](https://www.w3.org/TR/did-core/). Subject Identifiers in this format MUST contain a \"url\" member whose value is a DID URL for the DID Subject being identified.  The value of the \"url\" member MUST be a valid DID URL and MAY be a bare DID.  The \"url\" member is REQUIRED and MUST NOT be null or empty.  The Decentralized Identifier Format is identified by the name \"did\".
type Did struct {
	Format string `json:"format"`

	Url string `json:"url"`
}
