/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// [Spec](https://openid.net/specs/openid-sse-framework-1_0.html#rfc.section.3.4.2)  The \"SAML Assertion ID\" Subject Identifier Format specifies a SAML 2.0 [OASIS.saml-core-2.0-os](https://openid.net/specs/openid-sse-framework-1_0.html#OASIS.saml-core-2.0-os) assertion identifier.
type SamlAssertionId struct {
	Format string `json:"format"`
	// The \"Issuer\" value of the SAML assertion being identified, defined in [OASIS.saml-core-2.0-os](https://openid.net/specs/openid-sse-framework-1_0.html#OASIS.saml-core-2.0-os)
	Issuer string `json:"issuer"`
	// The \"ID\" value of the SAML assertion being identified, defined in [OASIS.saml-core-2.0-os](https://openid.net/specs/openid-sse-framework-1_0.html#OASIS.saml-core-2.0-os)
	AssertionId string `json:"assertion_id"`
}
