/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/i2-open/i2goSignals/internal/providers/dbProviders"
	ssef "github.com/i2-open/i2goSignals/internal/server"
	"github.com/i2-open/i2goSignals/pkg/constants"
	"github.com/i2-open/i2goSignals/pkg/logger"
	"github.com/i2-open/i2goSignals/pkg/nodeid"
	"github.com/i2-open/i2goSignals/pkg/tlsSupport"
)

var mLog = logger.Sub("MAIN")

// stripQuotes removes surrounding double or single quotes from a string
func stripQuotes(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func StartProvider(dbUrl string) (*dbProviders.Persistence, error) {

	name := "ssef"
	if found := stripQuotes(os.Getenv("DBNAME")); found != "" {
		mLog.Info("Using dbname", "name", found)
		name = found
	}

	return dbProviders.OpenPersistence(dbUrl, name)
}

func main() {
	logger.Init(logger.Options{
		Level:  os.Getenv("LOG_LEVEL"),
		Format: os.Getenv("LOG_FORMAT"),
		Attrs: logger.DefaultAttrs(
			"gosignals",
			constants.GoSignalsVersion,
			nodeid.Resolve(),
			os.Getenv("I2SIG_CLUSTER_NAME"),
		),
	})
	tlsSupport.CheckCaInstalled(nil)

	mLog.Info("i2goSignals server starting...", "version", constants.GoSignalsVersion)
	port := "8888"
	if found := stripQuotes(os.Getenv("PORT")); found != "" {
		port = found
	}

	dbUrl := ""
	if found := stripQuotes(os.Getenv("MONGO_URL")); found != "" {
		dbUrl = fmt.Sprintf("%v", found)
		mLog.Info("Connecting to MONGO_URL service", "url", dbUrl)
	} else {
		mLog.Info("MONGO_URL not set, using memory provider")
	}

	persistence, err := StartProvider(dbUrl)
	if err != nil {
		mLog.Error("Fatal: Unable to start database provider", "error", err)
		os.Exit(-1)
	}
	defer func(p *dbProviders.Persistence) {
		if p.Storage != nil {
			err := p.Storage.Close()
			if err != nil {
				mLog.Error("Fatal: Unable to close database provider", "error", err)
			}
		}
	}(persistence)

	baseUrl := "127.0.0.1:" + port + "/"
	if found := stripQuotes(os.Getenv("BASE_URL")); found != "" {
		baseUrl = found
	}
	mLog.Info("Base URL", "url", baseUrl)

	signalsApplication := ssef.StartServer(":"+port, persistence, baseUrl)

	closer, tlsMode, err := tlsSupport.InitTransportLayerSecurity(signalsApplication.Server)
	if err != nil {
		mLog.Error("Fatal: Unable to initialize TLS mode", "error", err)
		panic(err)
	}
	if closer != nil {
		defer func(closer io.Closer) {
			_ = closer.Close()
		}(closer)
	}
	mLog.Info("HTTP Listening", "tls", tlsMode, "port", port)
	if tlsMode {
		err = signalsApplication.Server.ListenAndServeTLS("", "")
	} else {
		mLog.Warn("TLS not enabled, using HTTP")
		err = signalsApplication.Server.ListenAndServe()
	}

	if err != nil {
		mLog.Error("Server error", "error", err)
		os.Exit(-1)
	}
}
