/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)

	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"Register",
		http.MethodPost,
		"/register",
		Register,
	},

	Route{
		"TriggerEvent",
		strings.ToUpper("Post"),
		"/trigger-event",
		TriggerEvent,
	},

	Route{
		"AddSubject",
		strings.ToUpper("Post"),
		"/add-subject",
		AddSubject,
	},

	Route{
		"GetStatus",
		strings.ToUpper("Get"),
		"/status",
		GetStatus,
	},

	Route{
		"RemoveSubject",
		strings.ToUpper("Post"),
		"/remove-subject",
		RemoveSubject,
	},

	Route{
		"StreamDelete",
		strings.ToUpper("Delete"),
		"/stream",
		StreamDelete,
	},

	Route{
		"StreamGet",
		strings.ToUpper("Get"),
		"/stream",
		StreamGet,
	},

	Route{
		"StreamPost",
		strings.ToUpper("Post"),
		"/stream",
		StreamPost,
	},

	Route{
		"UpdateStatus",
		strings.ToUpper("Post"),
		"/status",
		UpdateStatus,
	},

	Route{
		"VerificationRequest",
		strings.ToUpper("Post"),
		"/verification",
		VerificationRequest,
	},

	Route{
		"WellKnownSseConfigurationGet",
		strings.ToUpper("Get"),
		"/.well-known/sse-configuration",
		WellKnownSseConfigurationGet,
	},

	Route{
		"WellKnownSseConfigurationIssuerGet",
		strings.ToUpper("Get"),
		"/.well-known/sse-configuration/{issuer}",
		WellKnownSseConfigurationIssuerGet,
	},

	Route{
		"JwksJson",
		strings.ToUpper("Get"),
		"/jwks.json",
		JwksJson,
	},

	Route{
		"JwksJsonTenant",
		strings.ToUpper("Get"),
		"/jwks/{issuer}",
		JwksJsonIssuer,
	},

	Route{
		"PollEvents",
		strings.ToUpper("Post"),
		"/poll",
		PollEvents,
	},
}
