/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

// Transmitters have metadata describing their configuration. [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#discovery-meta) 
type TransmitterConfiguration struct {
	// URL using the https scheme with no query or fragment component that the Transmitter asserts as its Issuer Identifier. This MUST be identical to the iss claim value in Security Event Tokens issued from this Transmitter. 
	Issuer string `json:"issuer"`
	// URL of the Transmitter's [JSON Web Key Set](https://openid.net/specs/openid-sse-framework-1_0.html#RFC7517) document. This contains the signing key(s) the Receiver uses to validate signatures from the Transmitter. 
	JwksUri string `json:"jwks_uri"`
	// List of supported delivery method URIs. Recommended.
	DeliveryMethodsSupported []string `json:"delivery_methods_supported,omitempty"`
	// The URL of the Configuration Endpoint.
	ConfigurationEndpoint string `json:"configuration_endpoint,omitempty"`
	// The URL of the Status Endpoint.
	StatusEndpoint string `json:"status_endpoint,omitempty"`
	// The URL of the Add Subject Endpoint.
	AddSubjectEndpoint string `json:"add_subject_endpoint,omitempty"`
	// The URL of the Remove Subject Endpoint.
	RemoveSubjectEndpoint string `json:"remove_subject_endpoint,omitempty"`
	// The URL of the Verification Endpoint.
	VerificationEndpoint string `json:"verification_endpoint,omitempty"`
	// List of member names in a Complex Subject which, if present in a Subject Member in an event, MUST be interpreted by a Receiver. 
	CriticalSubjectMembers []string `json:"critical_subject_members,omitempty"`
}
