/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

// [Spec](https://openid.net/specs/openid-sse-framework-1_0.html#rfc.section.3.2)  A Complex Subject Member has a name and a value that is a JSON object that has one or more Simple Subject Members. All members within a Complex Subject MUST represent attributes of the same Subject Principal. As a whole, the Complex Subject MUST refer to exactly one Subject Principal.
type ComplexSubject struct {

	Application *AllOfComplexSubjectApplication `json:"application,omitempty"`

	Device *AllOfComplexSubjectDevice `json:"device,omitempty"`

	Group *AllOfComplexSubjectGroup `json:"group,omitempty"`

	OrgUnit *AllOfComplexSubjectOrgUnit `json:"org_unit,omitempty"`

	Session *AllOfComplexSubjectSession `json:"session,omitempty"`

	Tenant *AllOfComplexSubjectTenant `json:"tenant,omitempty"`

	User *AllOfComplexSubjectUser `json:"user,omitempty"`
}
