/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

// [Spec](https://datatracker.ietf.org/doc/html/draft-ietf-secevent-subject-identifiers#section-3.2.4)  The Email Identifier Format identifies a subject using an email address.  Subject Identifiers in this format MUST contain an \"email\" member whose value is a string containing the email address of the subject, formatted as an \"addr-spec\" as defined in Section 3.4.1 of [RFC5322](https://datatracker.ietf.org/doc/html/rfc5322). The \"email\" member is REQUIRED and MUST NOT be null or empty.  The value of the \"email\" member SHOULD identify a mailbox to which email may be delivered, in accordance with [RFC5321](https://datatracker.ietf.org/doc/html/rfc5321). The Email Identifier Format is identified by the name \"email\".
type Email struct {

	Format string `json:"format"`

	Email string `json:"email"`
}
