/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

// [Spec](https://datatracker.ietf.org/doc/html/draft-ietf-secevent-subject-identifiers#section-3.2.7)  The Phone Number Identifier Format identifies a subject using a telephone number.  Subject Identifiers in this format MUST contain a \"phone_number\" member whose value is a string containing the full telephone number of the subject, including international dialing prefix, formatted according to E.164 [E164](https://datatracker.ietf.org/doc/html/draft-ietf-secevent-subject-identifiers#ref-E164). The \"phone_number\" member is REQUIRED and MUST NOT be null or empty. The Phone Number Identifier Format is identified by the name \"phone_number\".
type PhoneNumber struct {

	Format string `json:"format"`

	PhoneNumber string `json:"phone_number"`
}
