/*
 * Stream Management API for OpenID Shared Security Events
 *
 * [OpenID Spec](https://openid.net/specs/openid-sse-framework-1_0.html#management)  HTTP API to be implemented by Event Transmitters. This API can be used by Event Receivers to query and update the Event Stream configuration and status, to add and remove subjects, and to trigger verification. 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

// [Spec](https://datatracker.ietf.org/doc/html/draft-ietf-secevent-subject-identifiers#section-3.2.1)  The Account Identifier Format identifies a subject using an account at a service provider, identified with an \"acct\" URI as defined in [RFC7565](https://datatracker.ietf.org/doc/html/rfc7565). Subject Identifiers in this format MUST contain a \"uri\" member whose value is the \"acct\" URI for the subject.  The \"uri\" member is REQUIRED and MUST NOT be null or empty.  The Account Identifier Format is identified by the name \"account\".
type Account struct {

	Format string `json:"format"`

	Uri string `json:"uri"`
}
